package com.geeknewbee.doraemon.processcenter.command;

public enum CommandType {
    PLAY_SOUND, MECHANICAL_MOVEMENT, SHOW_EXPRESSION, PLAY_MUSIC,
    WIFI_MESSAGE, SETTING_VOLUME, STOP, ACTIONSET, LE_XING_FOOT,
    BIND_ACCOUNT_SUCCESS, SHOW_QR, PLAY_LOCAL_RESOURCE, PLAY_JOKE, READ_SENCE, BLUETOOTH_CONTROL_FOOT
}
