package com.geeknewbee.doraemon.processcenter.command;

public enum CommandType {
    PLAY_SOUND, SHOW_EXPRESSION, PLAY_MUSIC,
    WIFI_MESSAGE, SETTING_VOLUME, STOP, SPORT_ACTION_SET, FOOT,
    BIND_ACCOUNT_SUCCESS, PLAY_LOCAL_RESOURCE, PLAY_JOKE, BLUETOOTH_CONTROL_FOOT,
    BL, BL_SP, TAKE_PICTURE, PLAY_MOVIE, SLEEP, LEARN_EN,
    PERSON_START, PERSON_ADD_FACE, PERSON_SET_NAME, PERSON_DELETE_ALL
}
