package com.geeknewbee.doraemon.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weather_CityDaoConfig;
    private final DaoConfig personDaoConfig;

    private final Weather_CityDao weather_CityDao;
    private final PersonDao personDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weather_CityDaoConfig = daoConfigMap.get(Weather_CityDao.class).clone();
        weather_CityDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        weather_CityDao = new Weather_CityDao(weather_CityDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);

        registerDao(Weather_City.class, weather_CityDao);
        registerDao(Person.class, personDao);
    }

    public void clear() {
        weather_CityDaoConfig.getIdentityScope().clear();
        personDaoConfig.getIdentityScope().clear();
    }

    public Weather_CityDao getWeather_CityDao() {
        return weather_CityDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

}
