/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_imscv_NaviPackSdk_NaviPackSdk_SdkMessageDealThread */

#ifndef _Included_com_imscv_NaviPackSdk_NaviPackSdk_SdkMessageDealThread
#define _Included_com_imscv_NaviPackSdk_NaviPackSdk_SdkMessageDealThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
